### ISSUE TITLE
Work on individual rows of a table

### ISSUE THREAD

**Issue by RahmanM** [aboudoux/BlazorAnimation#2]
Hi,
This is more like a question rather than issue. I am just looking at the code and I can't see how this will work in my scenario but please correct me if it works.

I have a list of rows and each row has a Complete and Delete actions when clicking the Complete button I would like to animate only that specific row similarly for the delete.

Just looking at the code and the Enable flag not sure if this will be doable? Do you think this will work in this scenario?

     @if (Todos != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Done?</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var todo in Todos)
                {
     // Animation to happen here per row??
                <tr>
                    <td><OverstrikeText Overstrike=@todo.Complete Text="@todo.Description"></OverstrikeText></td>
                    <td>@todo?.Category</td>
                    <td>
                        <BooleanToYesNo Condition="@todo.Complete" />
                    </td>
                    <td>
                        <a href="javascript: void(0);" @onclick="(() => deleteTodo(todo.Id))"><i class="far fa-trash-alt"></i></a> |
                        <a href="javascript: void(0);" @onclick="(() => flipComplete(todo.Id))"><i class="fas fa-check"></i></a>
                    </td>
                </tr>

                }

            </tbody>
        </table>

**Comment by aboudoux** [comment]
Hello, and thank you for your interest in BlazorAnimation

I have make a little test with the FetchData.razor code, it seem to work perfecly.
```
<table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Temp. (C)</th>
                <th>Temp. (F)</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var forecast in forecasts)
            {
                <Animation Effect="@Effect.ShakeX" Speed="@Speed.Fast" Enabled="(forecast.TemperatureC < 10)">
                <tr>
                    <td>@forecast.Date.ToShortDateString()</td>
                    <td>@forecast.TemperatureC</td>
                    <td>@forecast.TemperatureF</td>
                    <td>@forecast.Summary</td>
                </tr>
                </Animation>
            }
        </tbody>
    </table>
```

So I think your scenario is good
