### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by curelom** [aboudoux/BlazorAnimation#3]
Doesn't work at all.  Even bringing up in your example http://blazoranimation.boudoux.fr and it doesn't work.  No animation whatsoever.

**Comment by aboudoux** [comment]
Hello, and thanks for posting the issue.

The example site is working fine for me, so I think you are going through a proxy or firewall that is blocking the websocket communication or the download of some CSS or JS resources. I have already dealt with this kind of problem on an MVC project for which the administrators had defined a maximum size of 1MB for the CSS at the firewall level.

Check your browser debugger for more details, but I don't think the problem come from the library.
