### ISSUE TITLE
OnAnimationEnd error CS0154	

### ISSUE THREAD

**Issue by quyentruong** [aboudoux/BlazorAnimation#9]
Hello,

CS0154	The property or indexer 'Animation.OnAnimationEnd' cannot be used in this context because it lacks the get accessor

I got the error when trying to use OnAnimationEnd. The code still works fine, but the error keeping show up in Visual Studio is annoying.

**Comment by aboudoux** [comment]
I see what you mean. 
When you have a razor view opened with a OnAnimationEnd, VS show you a CS0154 in the "Error List", but if you close the view, the error disepear, right ?

**Comment by quyentruong** [comment]
Yes, it's correct.

**Comment by aboudoux** [comment]
Hello, I upgraded to VS 2022 17.7.4 and the problem seems to be resolved. Can you confirm that it's the same thing on your side?

**Comment by quyentruong** [comment]
You're right. I don't see the problem anymore.
